### ISSUE TITLE
Thoughts on manipulatable graph

### ISSUE THREAD

**Issue by cjstewa9** [jacobtnyoung/SAND#1]
I can think of three ways to approach creating a manipulatable graph. (1) Create 1 graph with a widget for each dimension. While this would allow students to play with multiple aspects of the graph at once, it could be overwhelming. (2) Create an individual .rmd for each graph dimension. This option would be less overwhelming for students and would make it easier to view isolated effects. However, they wouldn't be able to set different dimensions at different levels to see the effects. (3) We make both.

**Comment by jacobtnyoung** [comment]
Good point. Maybe we blend them. So the first page starts with one thing you can change, then a button the move to another page that adds a feature, and so on.
