### ISSUE TITLE
Week 1 potential ideas

### ISSUE THREAD

**Issue by jacobtnyoung** [jacobtnyoung/SAND#12]

**Comment by jacobtnyoung** [comment]
For week 1 I was thinking we should have ???

**Comment by cjstewa9** [comment]
Week 1 covers networks in the broadest terms possible. I think exposing the class to a complex graph that they can manipulate at this point could be overwhelming. Alternatively, providing the link to something like the Anderson data could gently introduce the class to network data in graph theoretic notation. While the graph can be manipulated, the widgets use language that is familiar to those who aren't familiar with networks vocabulary yet.
