### ISSUE TITLE
Cannot download github UserNetR package 

### ISSUE THREAD

**Issue by zelqadah** [jacobtnyoung/SAND#39]
I keep getting the following error message 

> install_github("DougLuke/UserNetR")
Error in install.github("DougLuke/UserNetR") : 
  could not find function "install.github"

**Comment by jacobtnyoung** [comment]
Hi @zelqadah ! Did you load the `devtools` package?

Try using:

```r

install.packages( "devtools" )

library( devtools )

```

`install_github()` is a function in the `devtools` package.

Let me know!

**Comment by zelqadah** [comment]
@jacobtnyoung I downloaded both the devtools and sna

I will try downloading devtools again

**Comment by zelqadah** [comment]
@jacobtnyoung I downloaded devtools and when I called it into the library I received the below issue 

library(devtools)
Loading required package: usethis
Error: package or namespace load failed for ‘devtools’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘stringi’

**Comment by jacobtnyoung** [comment]
Looks like there is a problem loading the dependent packages. Try this:

```r

install.packages( "stringi" )
library(stringi)

```

Note that the `UserNetR` package is just for the data that is used in the lab example.

**Comment by zelqadah** [comment]
IT WORKED! Thank you :)

**Comment by jacobtnyoung** [comment]
Great! @zelqadah
