### ISSUE TITLE
Issue running gplot function

### ISSUE THREAD

**Issue by zelqadah** [jacobtnyoung/SAND#40]
This is the code I am running 

+gplot( 
+     LondonGangMatrix, 
+     gmode = "graph",
+     edge.col="grey40", 
+     vertex.col="#3250a8",
+     vertex.cex = rescale( deg.LondonGangMatrix, 0.2, 4 ),
+     coord = coords,
+     main = "London Gang Network Degree Centrality (Undirected)",
+     sub = "node sized by degree centrality")

And this is the error I am getting 

Error: unexpected '=' in:
"    +     LondonGangMatrix, 
    +     gmode ="

this is happening for any plot that I try to run

**Comment by jacobtnyoung** [comment]
Hi @zelqadah . You are including a "+" sign that should not be there. Try this:

```r

gplot( 
LondonGangMatrix, 
gmode = "graph" 
)

```

It looks like you are copy and pasting from something and it is including the extra characters.
