### ISSUE TITLE
Issue reading in CSV file for undirected network

### ISSUE THREAD

**Issue by zelqadah** [jacobtnyoung/SAND#41]
LGMat<-as.matrix(read.csv(loc,as.is = TRUE,header = TRUE,row.names = 1))
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names
In addition: Warning messages:
1: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  line 1 appears to contain embedded nulls
2: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  line 2 appears to contain embedded nulls
3: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  incomplete final line found by readTableHeader on 'https://github.com/jacobtnyoung/sna-textbook/raw/main/data/data-london-gang-net.rds'

**Comment by zelqadah** [comment]
Figured it out!

**Comment by jacobtnyoung** [comment]
Great!
