### ISSUE TITLE
Finding attributes for the London Gang Net

### ISSUE THREAD

**Issue by mattduran12** [jacobtnyoung/SAND#42]
Hi Dr. Young,

For Homework #5, we are asked to evaluate attributes ('Prison', 'Convictions', and 'Birthplace') in the London Gang Network.

I'm having difficulty ascertaining where, in the network object, these attributes are, or finding a .csv file that contains the attribute information. Would you please help me? Below is the code in Lab 10 that I am looking to. Thanks!

# define the attributes object
attrs <- read.csv( 
    "https://raw.githubusercontent.com/jacobtnyoung/sna-textbook/main/data/data-PINS-w1-age-race-attributes.csv",
    as.is = TRUE,
    header = TRUE 
    )

# assign the attributes to the network
gaNetU %v% "Age" <- attrs[,1]
gaNetU %v% "Race" <- attrs[,2]

**Comment by jacobtnyoung** [comment]
Hi @mattduran12! They are stored in the object. You can seen this under the "Vertex attribute names:" header when you print out the `LondonGangNet` object.

For example:

```r


# load the libraries we need
library( sna )
library( network )
library( ergm )

# define the path location for the file
loc <- "https://github.com/jacobtnyoung/sna-textbook/raw/main/data/data-london-gang-net.rds"
LondonGangNet <- readRDS( url(loc ) )

# look at the network
LondonGangNet

```

The last line will show you the attributes. You can then reference them using the `%v%` operator. For example:

```r

# show the Age atttribute
LondonGangNet %v% "Age"

```

Note that `ergm` will recognize that these are attributes. So, you don't need to use the `%v%` operator when estimating a model. For example:

```r

# this works
ergm( LondonGangNet ~ edges + nodefactor( "Age" )

# this doesn't work
ergm( LondonGangNet ~ edges + nodefactor( LondonGangNet %v% "Age" )  )

```

Let me know if you still have questions!

**Comment by jacobtnyoung** [comment]
@mattduran12, if you are still running into issues, just reopen the issue and let me know.
